#!/usr/bin/env pwsh

# ESP32 BLE Server Upload and Client Setup Script
# Run this after connecting your ESP32-S3 to USB

Write-Host "🚀 ESP32 BLE Server Upload and Client Setup" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green

# Check if PlatformIO is available
if (-not (Get-Command pio -ErrorAction SilentlyContinue)) {
    Write-Host "❌ PlatformIO CLI not found. Please install PlatformIO first." -ForegroundColor Red
    Write-Host "Visit: https://platformio.org/install/cli" -ForegroundColor Yellow
    exit 1
}

# Check if ESP32 is connected
Write-Host "`n📱 Checking for connected ESP32..."
$ports = pio device list --json-output | ConvertFrom-Json
$esp32Port = $null
foreach ($port in $ports) {
    if ($port.description -like "*ESP32*" -or $port.description -like "*USB Serial*") {
        $esp32Port = $port.port
        break
    }
}

if (-not $esp32Port) {
    Write-Host "⚠️  No ESP32 detected. Please connect your ESP32-S3 via USB." -ForegroundColor Yellow
    Write-Host "Press Enter when ESP32 is connected..."
    Read-Host
}

# Upload firmware
Write-Host "`n⬆️  Uploading firmware to ESP32..."
try {
    pio run -e esp32s3-n16r8 -t upload
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ Firmware uploaded successfully!" -ForegroundColor Green
    } else {
        Write-Host "❌ Upload failed. Check your connections." -ForegroundColor Red
        exit 1
    }
} catch {
    Write-Host "❌ Upload error: $_" -ForegroundColor Red
    exit 1
}

# Monitor serial to get IP address
Write-Host "`n📡 Monitoring ESP32 serial output to get IP address..."
Write-Host "Press Ctrl+C when you see the IP address" -ForegroundColor Yellow
Write-Host "Looking for: 'WiFi connected! IP address: x.x.x.x'" -ForegroundColor Cyan

try {
    pio device monitor -e esp32s3-n16r8 --baud 115200
} catch {
    # User pressed Ctrl+C, continue
}

# Get IP address from user
Write-Host "`n🌐 Please enter the ESP32's IP address from the serial output:"
$esp32IP = Read-Host "IP Address (e.g., 192.168.1.100)"

if (-not $esp32IP) {
    Write-Host "❌ No IP address provided. Exiting." -ForegroundColor Red
    exit 1
}

# Validate IP format
if ($esp32IP -notmatch "^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$") {
    Write-Host "❌ Invalid IP address format. Exiting." -ForegroundColor Red
    exit 1
}

# Update client configuration
Write-Host "`n⚙️  Configuring React client..."

$envFile = @"
# ESP32 Server Configuration
VITE_API_BASE_URL=http://$esp32IP
VITE_WS_URL=ws://${esp32IP}:81

# Generated by setup script on $(Get-Date)
"@

try {
    $envFile | Out-File -FilePath "client\.env" -Encoding UTF8
    Write-Host "✅ Client .env file created successfully!" -ForegroundColor Green
} catch {
    Write-Host "❌ Failed to create .env file: $_" -ForegroundColor Red
    exit 1
}

# Install client dependencies and start
Write-Host "`n📦 Installing client dependencies..."
try {
    Set-Location client
    npm install
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ Dependencies installed successfully!" -ForegroundColor Green
    } else {
        Write-Host "❌ Failed to install dependencies." -ForegroundColor Red
        exit 1
    }
} catch {
    Write-Host "❌ Error installing dependencies: $_" -ForegroundColor Red
    exit 1
}

# Final instructions
Write-Host "`n🎉 Setup Complete!" -ForegroundColor Green
Write-Host "==================" -ForegroundColor Green
Write-Host "ESP32 Server: http://$esp32IP" -ForegroundColor Cyan
Write-Host "WebSocket:    ws://${esp32IP}:81" -ForegroundColor Cyan
Write-Host ""
Write-Host "To start the client dashboard:" -ForegroundColor Yellow
Write-Host "  cd client" -ForegroundColor White
Write-Host "  npm run dev" -ForegroundColor White
Write-Host ""
Write-Host "The React dashboard will connect to your ESP32 BLE server!" -ForegroundColor Green
Write-Host "You can now control BLE connection parameters with a beautiful web interface." -ForegroundColor Green

# Ask if user wants to start the client now
$startNow = Read-Host "`nStart the client dashboard now? (y/N)"
if ($startNow -eq "y" -or $startNow -eq "Y") {
    Write-Host "`n🌐 Starting React client..."
    npm run dev
}